apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: zxkfall/kub-demo-users
