apiVersion: apps/v1
kind: Deployment
metadata: 
  name: second-app-deploymnet
  labels:
    group: example

spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: second-app
      tier: backend
    # matchExpressions:
    #   - {key: app, operator: In, values: [second-app, first-app]}

  template: 
    metadata: 
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: nginx
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 5
